version: "2"

run:
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  default: none
  enable:
    - dupl
    - errcheck
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
        path: api/*
      - linters:
          - dupl
          - lll
        path: internal/*
      # Allow dot-imports in these specific helper files
      - path: '(^|.*/)[test|internal]/utils/[utils|shared]\.go$'
        linters:
          - staticcheck
        text: '^ST1001: should not use dot imports'
      # Also allow in any *_test.go file
      - path: '.*_test\.go$'
        linters:
          - staticcheck
        text: '^ST1001: should not use dot imports'
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$