apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: expiring-secrets
    prometheus: k8s
    role: alert-rules
  name: expiring-secret-operator-expired-secret-rules
spec:
  groups:
  - name: expired-secret.rules
    rules:
    - alert: SecretExpirationDateIsApproaching
      annotations:
        description: The secret '{{ $labels.secret_name }}' in namespace '{{ $labels.secret_namespace
          }}' has passed its info threshold.
        summary: Secret expiration date is approaching
      expr: expiringsecrets_monitor_state{state="Info"} == 1
      for: 10m
      labels:
        severity: info
    - alert: SecretExpirationDateIsApproachingRapidly
      annotations:
        description: The secret '{{ $labels.secret_name }}' in namespace '{{ $labels.secret_namespace
          }}' has passed its warning threshold.
        summary: Secret expiration date is approaching rapidly
      expr: expiringsecrets_monitor_state{state="Warning"} == 1
      for: 5m
      labels:
        severity: warning
    - alert: SecretExpirationDateIsCritical
      annotations:
        description: The secret '{{ $labels.secret_name }}' in namespace '{{ $labels.secret_namespace
          }}' has passed its critical threshold.
        summary: Secret expiration date is critical
      expr: expiringsecrets_monitor_state{state="Critical"} == 1
      for: 5m
      labels:
        severity: critical
    - alert: SecretHasExpired
      annotations:
        description: The secret '{{ $labels.secret_name }}' in namespace '{{ $labels.secret_namespace
          }}' has expired.
        summary: Secret has expired
      expr: expiringsecrets_monitor_state{state="Expired"} == 1
      for: 5m
      labels:
        severity: critical
    - alert: SecretMonitorError
      annotations:
        description: The Monitor '{{ $labels.monitor_name }}' in namespace '{{ $labels.monitor_namespace
          }}' cannot evaluate secret '{{ $labels.secret_name }}'. Expiry is unknown.
        summary: Secret monitor cannot evaluate expiry
      expr: expiringsecrets_monitor_state{state="Error"} == 1
      for: 15m
      labels:
        severity: warning
