apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: expiring-secret-operator-metrics-reader
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: expiring-secrets
  name: expiring-secret-operator-metrics-reader-token
type: kubernetes.io/service-account-token
